### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mtreerungroj** [mtreerungroj/phr-web-app#1]
**note: only doctor/nurse use this!!**
- [x] connect project to Firebase.
- [x] login form (email, password, submit, new account, reset password).
- [x] user can regist new account. -> doctor/nurse
- [ ] if nurse, generate pin code for nurse: unique 4 digits
- [x] user can login.
- [x] user can logout.
- [ ] user can reset password.

**note: need only userid from Firebase**
- [ ] all profile data collected in hadoop database: Profile table.
- [ ] 4 digits collected in hadoop database: Pincode table.
